### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by apgapg** [euforic/azure-pipeline-gpt-pr-review#4]
![image](https://github.com/euforic/azure-pipeline-gpt-pr-review/assets/13887407/c796d4e2-d1a6-4ee4-a31a-2a840a053aa9)

Hi, Receiving following error

`##[error]File not found: '/azp/_work/_tasks/AIPRReview_018f87db-0fa6-79f2-8a8a-7661bb024ef4/0.12.3/dist/index.js'`

what could be the reason

**Comment by jpitapeva** [comment]
review this point in your code


"execution": {
    "Node10": {
      "target": "review.js"
    }
  }

**Comment by lordsteggu** [comment]
I have this issue as well, reviewing a c# web api application

**Comment by euforic** [comment]
@lordsteggu @jpitapeva just rebuilt and pushed. Sorry for the late response.

**Comment by jpitapeva** [comment]
> @lordsteggu @jpitapeva just rebuilt and pushed. Sorry for the late response.

Thank u ;)

**Comment by euforic** [comment]
closing for now feel free to reopen if there is still an issue
